sudo: required

language: c

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - export REPO=okdocker/nginx
    - PAGESPEED_VERSION=1.12.34.2
  matrix:
    - NGINX_VERSION=1.13.3 VARIANT=mainline
    - NGINX_VERSION=1.12.1 VARIANT=stable

install:
  - curl -O -L https://github.com/grammarly/rocker/releases/download/1.3.1/rocker-1.3.1-linux_amd64.tar.gz
  - tar xvfz rocker-1.3.1-linux_amd64.tar.gz

script:
  - ./rocker build --auth $DOCKER_USER:$DOCKER_PASS --push -var TravisBuildNumber=$TRAVIS_BUILD_NUMBER -var Commit=$COMMIT -var DockerImage=$REPO:$NGINX_VERSION -var NginxVersion=$NGINX_VERSION -var NginxVariant=$NGINX_VARIANT -var PagespeedVersion=$PAGESPEED_VERSION
  - ./rocker build --auth $DOCKER_USER:$DOCKER_PASS --push -var TravisBuildNumber=$TRAVIS_BUILD_NUMBER -var Commit=$COMMIT -var DockerImage=$REPO:$VARIANT -var NginxVersion=$NGINX_VERSION -var NginxVariant=$NGINX_VARIANT -var PagespeedVersion=$PAGESPEED_VERSION

